### ISSUE TITLE
TOS violation with account removal

### ISSUE THREAD

**Issue by Martii** [TriMoon/openuserjs.org#1]
OUJS has made a change recently to require SPDX codes for OSI approved licensing.

In order to improve the appearance of your script homepages it would be appreciated if you could modify all of your affected scripts.

Currently your Content License is:
https://github.com/TriMoon/openuserjs.org/blob/be5165908c9dd7c1daa73f70f37719a99921f9be/FB-App%20Widescreen.user.js#L20

You need to do several things in order to post new scripts and update existing ones.

1. Declare a Code License, perhaps `MIT`
2. Change the dual-licensing License Type to be a SPDX code to allow derivatives.

Until this change is made you will be unable to update those affected scripts... plus since you claim no derivatives that is in violation of the TOS and incongruent with GH here at https://github.com/TriMoon/openuserjs.org/blob/be5165908c9dd7c1daa73f70f37719a99921f9be/LICENSE which has `http://creativecommons.org/licenses/by-nc-sa/4.0/` . You will have a short period before your scripts are removed unless you fix this.

If `MIT` is chosen then it would look like this:
```
// @license			CC-BY-NC-SA-4.0;	http://creativecommons.org/licenses/by-nc-sa/4.0/
// @license			MIT
```

Thanks,
OUJS Staff

**Comment by Martii** [comment]
Bump

**Comment by TriMoon** [comment]
The LICENSE file on the GH link is a general one for scripts that lack proper license mentions inside the files i place. (Sort of a fallback for me)

I am NOT willing to change my license inside the scripts i produce, if OUJS does not want to provide the license selection i as an author choose, then your option is to indeed remove it from your site without duplicating in any form under a different license.

Yes Authors will dictate the license THEY want to use, not the hosting sites...

**Comment by Martii** [comment]
> then your option is to indeed remove it from your site without duplicating in any form under a different license.

Thanks for getting back on this isssue. Our options via the TOS is to remove the scripts for sure.

> not the hosting sites..

This to me seems like you don't agree with the TOS so  I will remove your account as well.

Have a nice day.

**Comment by TriMoon** [comment]
On to the next user script hosting site for all of us then.... https://github.com/TriMoon/openuserjs.org/commit/c21cec4790bae8de7bebe99612627ea65c66f39d
You guys started nice but ended badly and so fast....shame...
